name: Testing

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure project
        working-directory: ./
        run: cmake -S ./ -B ./build -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        working-directory: ./
        run: cmake --build ./build --target prototype_test

      - name: Testing project
        working-directory: ./build
        run: ./prototype_test
